### ISSUE TITLE
Species  average abundance bounce back when initial_averag_abundnace is small (say 5)

### ISSUE THREAD

**Issue by Mmyahaya** [b-cubed-eu/gcube#34]
In the simulate_random_walk function which supposed to set the subsequent lambda values to zero when first lambda value become zero, returned samples which subsequent values are not all zeros after the first zero. For instance,

```
simulate_random_walk(initial_average_abundance = 2,
                        n_time_points = 50,
                        sd_step = 1,
                        seed = NA)
```
returned
```
[1] 2 0 0 0 1 1 3 3 1 6 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[44] 0 0 0 0 0 0 0
```
is the function actually to return 'rpois(...)'?
```
#Return samples from Poisson
  return(rpois(n_time_points, lambdas))
```

**Comment by wlangera** [comment]
@Mmyahaya can you checkout the branch **tempcorr** and try again?

I do not think this problem still happens in the latest version.
In that version indeed we no longer return `rpois()` samples but the lambda values. So that is definitely fixed already.

**Comment by Mmyahaya** [comment]
Yes, it is fixed now
